# Generated by Django 4.0.5 on 2022-06-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_errorlog_alter_inventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
