# Generated by Django 4.0.5 on 2022-06-11 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0005_alter_inventory_inventory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentContainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_code', models.UUIDField(default=uuid.uuid4)),
                ('inventory_count', models.PositiveIntegerField(default=1)),
                ('added_products', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopify.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventor_per_shipment', models.ManyToManyField(to='shopify.shipmentcontainer')),
            ],
        ),
    ]
