# Generated by Django 4.0.5 on 2022-06-11 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0006_shipmentcontainer_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
