# Generated by Django 4.0.5 on 2022-06-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0007_shipment_shipment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='state',
            field=models.CharField(choices=[('CREATE', 'CREATE'), ('LIST', 'LIST'), ('GET', 'GET'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], default='CREATE', max_length=25),
        ),
    ]
