# Generated by Django 4.0.5 on 2022-06-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0008_errorlog_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
