# Generated by Django 4.0.5 on 2022-06-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0012_rename_inventor_per_shipment_shipment_inventory_per_shipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentcontainer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
